import sys
import unittest

sys.path.append('../app/controllers')
sys.path.append('../app/')

from appointment import *
from user import *
from role import *
from datetime import date

class TestAppointment(unittest.TestCase):
	 ###########################################      
  #   Pruebas para insertAppointment        #
  ###########################################
	def testInsertAppointment(self):
		user_controller = user()
		fecha = date(2016,7,1)
		appointment_controller = appointment()
		user_controller.insertUser(12345678,'doctortest','pass','name','last','doctorest@gmail.com',1)
		user_controller.insertUser(66666666,'pacientetest','pass','name','last','pacientetest@gmail.com',2)
		appointment_controller.insertAppointment(66666666,12345678,fecha,'descripcion')
		user_controller.deleteUser('doctortest')
		user_controller.deleteUser('pacientetest')
		appointment_controller.deleteAppointment(2)
	def testInsertAppointmentTrue(self):
		user_controller = user()
		fecha = date(2016,7,1)
		appointment_controller = appointment()
		user_controller.insertUser(12345678,'doctortest','pass','name','last','doctorest@gmail.com',1)
		user_controller.insertUser(66666666,'pacientetest','pass','name','last','pacientetest@gmail.com',2)
		result = appointment_controller.insertAppointment(66666666,12345678,fecha,'descripcion')
		user_controller.deleteUser('doctortest')
		user_controller.deleteUser('pacientetest')
		appointment_controller.deleteAppointment(2)
		self.assertTrue(result)
	def testInsertAppointmentDoctorNotExists(self):
		user_controller = user()
		fecha = date(2016,7,1)
		appointment_controller = appointment()
		user_controller.insertUser(12345678,'doctortest','pass','name','last','doctorest@gmail.com',1)
		user_controller.insertUser(66666666,'pacientetest','pass','name','last','pacientetest@gmail.com',2)
		result = appointment_controller.insertAppointment(66666666,123456789,fecha,'descripcion')
		user_controller.deleteUser('doctortest')
		user_controller.deleteUser('pacientetest')
		appointment_controller.deleteAppointment(2)
		self.assertFalse(result)
	def testInsertAppointmentPatientNotExists(self):
		user_controller = user()
		fecha = date(2016,7,1)
		appointment_controller = appointment()
		user_controller.insertUser(12345678,'doctortest','pass','name','last','doctorest@gmail.com',1)
		user_controller.insertUser(66666666,'pacientetest','pass','name','last','pacientetest@gmail.com',2)
		result = appointment_controller.insertAppointment(6666666,123456789,fecha,'descripcion')
		user_controller.deleteUser('doctortest')
		user_controller.deleteUser('pacientetest')
		appointment_controller.deleteAppointment(2)
		self.assertFalse(result)
	def testInsertAppointmentSameCi(self):
		user_controller = user()
		fecha = date(2016,7,1)
		appointment_controller = appointment()
		user_controller.insertUser(12345678,'doctortest','pass','name','last','doctorest@gmail.com',1)
		user_controller.insertUser(66666666,'pacientetest','pass','name','last','pacientetest@gmail.com',2)
		result = appointment_controller.insertAppointment(6666666,6666666,fecha,'descripcion')
		user_controller.deleteUser('doctortest')
		user_controller.deleteUser('pacientetest')
		appointment_controller.deleteAppointment(2)
		self.assertFalse(result)
	def testInsertAppointmentNotValidCiDoc(self):
		user_controller = user()
		fecha = date(2016,7,1)
		appointment_controller = appointment()
		user_controller.insertUser(12345678,'doctortest','pass','name','last','doctorest@gmail.com',1)
		user_controller.insertUser(66666666,'pacientetest','pass','name','last','pacientetest@gmail.com',2)
		result = appointment_controller.insertAppointment(66666666,'12345678',fecha,'descripcion')
		user_controller.deleteUser('doctortest')
		user_controller.deleteUser('pacientetest')
		appointment_controller.deleteAppointment(2)
		self.assertFalse(result)
	def testInsertAppointmentNotValidCiPatient(self):
		user_controller = user()
		fecha = date(2016,7,1)
		appointment_controller = appointment()
		user_controller.insertUser(12345678,'doctortest','pass','name','last','doctorest@gmail.com',1)
		user_controller.insertUser(66666666,'pacientetest','pass','name','last','pacientetest@gmail.com',2)
		result = appointment_controller.insertAppointment('66666666',12345678,fecha,'descripcion')
		user_controller.deleteUser('doctortest')
		user_controller.deleteUser('pacientetest')
		appointment_controller.deleteAppointment(2)
		self.assertFalse(result)
	def testInsertAppointmentNotValidDate(self):
		user_controller = user()
		fecha = date(2016,7,1)
		appointment_controller = appointment()
		user_controller.insertUser(12345678,'doctortest','pass','name','last','doctorest@gmail.com',1)
		user_controller.insertUser(66666666,'pacientetest','pass','name','last','pacientetest@gmail.com',2)
		result = appointment_controller.insertAppointment(66666666,12345678,'2016-08-01','descripcion')
		user_controller.deleteUser('doctortest')
		user_controller.deleteUser('pacientetest')
		appointment_controller.deleteAppointment(2)
		self.assertFalse(result)
	def testInsertAppointmentNotValidDescription(self):
		user_controller = user()
		fecha = date(2016,7,1)
		appointment_controller = appointment()
		user_controller.insertUser(12345678,'doctortest','pass','name','last','doctorest@gmail.com',1)
		user_controller.insertUser(66666666,'pacientetest','pass','name','last','pacientetest@gmail.com',2)
		result = appointment_controller.insertAppointment(66666666,12345678,fecha,12)
		user_controller.deleteUser('doctortest')
		user_controller.deleteUser('pacientetest')
		appointment_controller.deleteAppointment(2)
		self.assertFalse(result)
	def testInsertAppointmentNotValidDescription2(self):
		user_controller = user()
		fecha = date(2016,7,1)
		appointment_controller = appointment()
		user_controller.insertUser(12345678,'doctortest','pass','name','last','doctorest@gmail.com',1)
		user_controller.insertUser(66666666,'pacientetest','pass','name','last','pacientetest@gmail.com',2)
		result = appointment_controller.insertAppointment(66666666,12345678,fecha,'')
		user_controller.deleteUser('doctortest')
		user_controller.deleteUser('pacientetest')
		appointment_controller.deleteAppointment(2)
		self.assertFalse(result)
	def testInsertAppointmentOtherRole(self):
		user_controller = user()
		role_controller = role()
		role_controller.createRole('rol') #Tendra id 5 si solo hay 4 roles creados
		fecha = date(2016,7,1)
		appointment_controller = appointment()
		user_controller.insertUser(12345678,'doctortest','pass','name','last','doctorest@gmail.com',1)
		user_controller.insertUser(66666666,'pacientetest','pass','name','last','pacientetest@gmail.com',5)
		result = appointment_controller.insertAppointment(66666666,12345678,fecha,'descripcion')
		user_controller.deleteUser('doctortest')
		user_controller.deleteUser('pacientetest')
		role_controller.deleteRole(5)
		appointment_controller.deleteAppointment(2)
		self.assertTrue(result)
	 ###########################################      
  #   Pruebas para modifyAppointment        #
  ###########################################
	def testModifyAppointment(self):
		user_controller = user()
		fecha = date(2016,7,1)
		fecha2 = date(2016,8,1)
		appointment_controller = appointment()
		user_controller.insertUser(12345678,'doctortest','pass','name','last','doctorest@gmail.com',1)
		user_controller.insertUser(66666666,'pacientetest','pass','name','last','pacientetest@gmail.com',2)
		appointment_controller.insertAppointment(66666666,12345678,fecha,'descripcion')
		appointment_controller.modifyAppointment(2,fecha2,'descripcion nueva')
		user_controller.deleteUser('doctortest')
		user_controller.deleteUser('pacientetest')
		appointment_controller.deleteAppointment(2)
	def testModifyAppointmentTrue(self):
		user_controller = user()
		fecha = date(2016,7,1)
		fecha2 = date(2016,8,1)
		appointment_controller = appointment()
		user_controller.insertUser(12345678,'doctortest','pass','name','last','doctorest@gmail.com',1)
		user_controller.insertUser(66666666,'pacientetest','pass','name','last','pacientetest@gmail.com',2)
		appointment_controller.insertAppointment(66666666,12345678,fecha,'descripcion')
		result = appointment_controller.modifyAppointment(2,fecha2,'descripcion nueva')
		user_controller.deleteUser('doctortest')
		user_controller.deleteUser('pacientetest')
		appointment_controller.deleteAppointment(2)
		self.assertTrue(result)

	def testModifyAppointmentBadDate(self):
		user_controller = user()
		fecha = date(2016,7,1)
		fecha2 = '2016-08-01'
		appointment_controller = appointment()
		user_controller.insertUser(12345678,'doctortest','pass','name','last','doctorest@gmail.com',1)
		user_controller.insertUser(66666666,'pacientetest','pass','name','last','pacientetest@gmail.com',2)
		appointment_controller.insertAppointment(66666666,12345678,fecha,'descripcion')
		result = appointment_controller.modifyAppointment(2,fecha2,'descripcion nueva')
		user_controller.deleteUser('doctortest')
		user_controller.deleteUser('pacientetest')
		appointment_controller.deleteAppointment(2)
		self.assertFalse(result)

	def testModifyAppointmentBadDescription(self):
		user_controller = user()
		fecha = date(2016,7,1)
		fecha2 = '2016-08-01'
		appointment_controller = appointment()
		user_controller.insertUser(12345678,'doctortest','pass','name','last','doctorest@gmail.com',1)
		user_controller.insertUser(66666666,'pacientetest','pass','name','last','pacientetest@gmail.com',2)
		appointment_controller.insertAppointment(66666666,12345678,fecha,'descripcion')
		result = appointment_controller.modifyAppointment(2,fecha,1)
		user_controller.deleteUser('doctortest')
		user_controller.deleteUser('pacientetest')
		appointment_controller.deleteAppointment(2)
		self.assertFalse(result)

	def testModifyAppointmentBadDescription2(self):
		user_controller = user()
		fecha = date(2016,7,1)
		fecha2 = '2016-08-01'
		appointment_controller = appointment()
		user_controller.insertUser(12345678,'doctortest','pass','name','last','doctorest@gmail.com',1)
		user_controller.insertUser(66666666,'pacientetest','pass','name','last','pacientetest@gmail.com',2)
		appointment_controller.insertAppointment(66666666,12345678,fecha,'descripcion')
		result = appointment_controller.modifyAppointment(2,fecha,'')
		user_controller.deleteUser('doctortest')
		user_controller.deleteUser('pacientetest')
		appointment_controller.deleteAppointment(2)
		self.assertFalse(result)

	def testModifyAppointmentNotExistAppointment(self):
		user_controller = user()
		fecha = date(2016,7,1)
		fecha2 = '2016-08-01'
		appointment_controller = appointment()
		user_controller.insertUser(12345678,'doctortest','pass','name','last','doctorest@gmail.com',1)
		user_controller.insertUser(66666666,'pacientetest','pass','name','last','pacientetest@gmail.com',2)
		appointment_controller.insertAppointment(66666666,12345678,fecha,'descripcion')
		result = appointment_controller.modifyAppointment(6,fecha,'descripcion')
		user_controller.deleteUser('doctortest')
		user_controller.deleteUser('pacientetest')
		appointment_controller.deleteAppointment(2)
		self.assertFalse(result)

	 ###########################################      
  #   Pruebas para deleteAppointment        #
  ###########################################
	def testDeleteAppointment(self):
		user_controller = user()
		fecha = date(2016,7,1)
		fecha2 = date(2016,8,1)
		appointment_controller = appointment()
		user_controller.insertUser(12345678,'doctortest','pass','name','last','doctorest@gmail.com',1)
		user_controller.insertUser(66666666,'pacientetest','pass','name','last','pacientetest@gmail.com',2)
		appointment_controller.insertAppointment(66666666,12345678,fecha,'descripcion')
		appointment_controller.deleteAppointment(2)
		user_controller.deleteUser('doctortest')
		user_controller.deleteUser('pacientetest')
	def testDeleteAppointmentTrue(self):
		user_controller = user()
		fecha = date(2016,7,1)
		fecha2 = date(2016,8,1)
		appointment_controller = appointment()
		user_controller.insertUser(12345678,'doctortest','pass','name','last','doctorest@gmail.com',1)
		user_controller.insertUser(66666666,'pacientetest','pass','name','last','pacientetest@gmail.com',2)
		appointment_controller.insertAppointment(66666666,12345678,fecha,'descripcion')
		result = 		appointment_controller.deleteAppointment(2)
		user_controller.deleteUser('doctortest')
		user_controller.deleteUser('pacientetest')
		appointment_controller.deleteAppointment(2)
		self.assertTrue(result)
	def testDeleteAppointmentNotExistsAppointment(self):
		user_controller = user()
		fecha = date(2016,7,1)
		fecha2 = date(2016,8,1)
		appointment_controller = appointment()
		user_controller.insertUser(12345678,'doctortest','pass','name','last','doctorest@gmail.com',1)
		user_controller.insertUser(66666666,'pacientetest','pass','name','last','pacientetest@gmail.com',2)
		appointment_controller.insertAppointment(66666666,12345678,fecha,'descripcion')
		result = 		appointment_controller.deleteAppointment(6)
		user_controller.deleteUser('doctortest')
		user_controller.deleteUser('pacientetest')
		appointment_controller.deleteAppointment(2)
		self.assertFalse(result)
	def testDeleteAppointmentIdNotValid(self):
		user_controller = user()
		fecha = date(2016,7,1)
		fecha2 = date(2016,8,1)
		appointment_controller = appointment()
		user_controller.insertUser(12345678,'doctortest','pass','name','last','doctorest@gmail.com',1)
		user_controller.insertUser(66666666,'pacientetest','pass','name','last','pacientetest@gmail.com',2)
		appointment_controller.insertAppointment(66666666,12345678,fecha,'descripcion')
		result = 		appointment_controller.deleteAppointment('2')
		user_controller.deleteUser('doctortest')
		user_controller.deleteUser('pacientetest')
		appointment_controller.deleteAppointment(2)
		self.assertFalse(result)
	 ###########################################      
  # Pruebas para getAppointmentsByPatient   #
  ###########################################
	def testGetAppointmentByPatient(self):
		user_controller = user()
		fecha = date(2016,7,1)
		fecha2 = date(2016,8,1)
		appointment_controller = appointment()
		user_controller.insertUser(12345678,'doctortest','pass','name','last','doctorest@gmail.com',1)
		user_controller.insertUser(66666666,'pacientetest','pass','name','last','pacientetest@gmail.com',2)
		appointment_controller.insertAppointment(66666666,12345678,fecha,'descripcion')
		appointment_controller.getAppointmentsByPatient(6666666)
		user_controller.deleteUser('doctortest')
		user_controller.deleteUser('pacientetest')
		appointment_controller.deleteAppointment(2)
	def testGetAppointmentByPatientNotNull(self):
		user_controller = user()
		fecha = date(2016,7,1)
		fecha2 = date(2016,8,1)
		appointment_controller = appointment()
		user_controller.insertUser(12345678,'doctortest','pass','name','last','doctorest@gmail.com',1)
		user_controller.insertUser(66666666,'pacientetest','pass','name','last','pacientetest@gmail.com',2)
		appointment_controller.insertAppointment(66666666,12345678,fecha,'descripcion')
		result = appointment_controller.getAppointmentsByPatient(66666666)
		user_controller.deleteUser('doctortest')
		user_controller.deleteUser('pacientetest')
		appointment_controller.deleteAppointment(2)
		self.assertNotEqual(result,[])
	def testGetAppointmentByPatientNoAppointments(self):
		user_controller = user()
		fecha = date(2016,7,1)
		fecha2 = date(2016,8,1)
		appointment_controller = appointment()
		user_controller.insertUser(12345678,'doctortest','pass','name','last','doctorest@gmail.com',1)
		user_controller.insertUser(66666666,'pacientetest','pass','name','last','pacientetest@gmail.com',2)
		#appointment_controller.insertAppointment(66666666,12345678,fecha,'descripcion')
		result = appointment_controller.getAppointmentsByPatient(66666666)
		user_controller.deleteUser('doctortest')
		user_controller.deleteUser('pacientetest')
		appointment_controller.deleteAppointment(2)
		self.assertEqual(result,[])
	def testGetAppointmentByPatientNotExistsPatient(self):
		user_controller = user()
		fecha = date(2016,7,1)
		fecha2 = date(2016,8,1)
		appointment_controller = appointment()
		user_controller.insertUser(12345678,'doctortest','pass','name','last','doctorest@gmail.com',1)
		user_controller.insertUser(66666666,'pacientetest','pass','name','last','pacientetest@gmail.com',2)
		appointment_controller.insertAppointment(66666666,12345678,fecha,'descripcion')
		result = appointment_controller.getAppointmentsByPatient(66666663)
		user_controller.deleteUser('doctortest')
		user_controller.deleteUser('pacientetest')
		appointment_controller.deleteAppointment(2)
		self.assertEqual(result,[])
	def testGetAppointmentByPatientNotValidCi(self):
		user_controller = user()
		fecha = date(2016,7,1)
		fecha2 = date(2016,8,1)
		appointment_controller = appointment()
		user_controller.insertUser(12345678,'doctortest','pass','name','last','doctorest@gmail.com',1)
		user_controller.insertUser(66666666,'pacientetest','pass','name','last','pacientetest@gmail.com',2)
		appointment_controller.insertAppointment(66666666,12345678,fecha,'descripcion')
		result = appointment_controller.getAppointmentsByPatient('66666666')
		user_controller.deleteUser('doctortest')
		user_controller.deleteUser('pacientetest')
		appointment_controller.deleteAppointment(2)
		self.assertFalse(result)
	 ###########################################      
  # Pruebas para getAppointmentsByDoctor   #
  ###########################################
	def testGetAppointmentByDoctor(self):
		user_controller = user()
		fecha = date(2016,7,1)
		fecha2 = date(2016,8,1)
		appointment_controller = appointment()
		user_controller.insertUser(12345678,'doctortest','pass','name','last','doctorest@gmail.com',1)
		user_controller.insertUser(66666666,'pacientetest','pass','name','last','pacientetest@gmail.com',2)
		appointment_controller.insertAppointment(66666666,12345678,fecha,'descripcion')
		appointment_controller.getAppointmentsByDoctor(12345678)
		user_controller.deleteUser('doctortest')
		user_controller.deleteUser('pacientetest')
		appointment_controller.deleteAppointment(2)
	def testGetAppointmentByDoctorNotNull(self):
		user_controller = user()
		fecha = date(2016,7,1)
		fecha2 = date(2016,8,1)
		appointment_controller = appointment()
		user_controller.insertUser(12345678,'doctortest','pass','name','last','doctorest@gmail.com',1)
		user_controller.insertUser(66666666,'pacientetest','pass','name','last','pacientetest@gmail.com',2)
		appointment_controller.insertAppointment(66666666,12345678,fecha,'descripcion')
		result = appointment_controller.getAppointmentsByDoctor(12345678)
		user_controller.deleteUser('doctortest')
		user_controller.deleteUser('pacientetest')
		appointment_controller.deleteAppointment(2)
		self.assertNotEqual(result,[])
	def testGetAppointmentByDoctorNoAppointments(self):
		user_controller = user()
		fecha = date(2016,7,1)
		fecha2 = date(2016,8,1)
		appointment_controller = appointment()
		user_controller.insertUser(12345678,'doctortest','pass','name','last','doctorest@gmail.com',1)
		user_controller.insertUser(66666666,'pacientetest','pass','name','last','pacientetest@gmail.com',2)
		#appointment_controller.insertAppointment(66666666,12345678,fecha,'descripcion')
		result = appointment_controller.getAppointmentsByDoctor(12345678)
		user_controller.deleteUser('doctortest')
		user_controller.deleteUser('pacientetest')
		appointment_controller.deleteAppointment(2)
		self.assertEqual(result,[])
	def testGetAppointmentByDoctorNotExistsDoctor(self):
		user_controller = user()
		fecha = date(2016,7,1)
		fecha2 = date(2016,8,1)
		appointment_controller = appointment()
		user_controller.insertUser(12345678,'doctortest','pass','name','last','doctorest@gmail.com',1)
		user_controller.insertUser(66666666,'pacientetest','pass','name','last','pacientetest@gmail.com',2)
		appointment_controller.insertAppointment(66666666,12345678,fecha,'descripcion')
		result = appointment_controller.getAppointmentsByDoctor(12345679)
		user_controller.deleteUser('doctortest')
		user_controller.deleteUser('pacientetest')
		appointment_controller.deleteAppointment(2)
		self.assertEqual(result,[])
	def testGetAppointmentByDoctorNotValidCi(self):
		user_controller = user()
		fecha = date(2016,7,1)
		fecha2 = date(2016,8,1)
		appointment_controller = appointment()
		user_controller.insertUser(12345678,'doctortest','pass','name','last','doctorest@gmail.com',1)
		user_controller.insertUser(66666666,'pacientetest','pass','name','last','pacientetest@gmail.com',2)
		appointment_controller.insertAppointment(66666666,12345678,fecha,'descripcion')
		result = appointment_controller.getAppointmentsByDoctor('12345678')
		user_controller.deleteUser('doctortest')
		user_controller.deleteUser('pacientetest')
		appointment_controller.deleteAppointment(2)
		self.assertFalse(result)



if __name__ == '__main__':
	unittest.main()