"""empty message

Revision ID: 35e341306891
Revises: None
Create Date: 2016-05-19 16:49:38.732879

"""

# revision identifiers, used by Alembic.
revision = '35e341306891'
down_revision = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('User', sa.Column('password', sa.String(length=16), nullable=True))
    op.add_column('User', sa.Column('username', sa.String(length=50), nullable=True))
    op.create_unique_constraint(None, 'User', ['username'])
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'User', type_='unique')
    op.drop_column('User', 'username')
    op.drop_column('User', 'password')
    ### end Alembic commands ###
