"""empty message

Revision ID: 364ce360b234
Revises: None
Create Date: 2016-05-25 22:17:47.329689

"""

# revision identifiers, used by Alembic.
revision = '364ce360b234'
down_revision = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(None, 'User', 'Role', ['role'], ['id'])
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'User', type_='foreignkey')
    ### end Alembic commands ###
