"""empty message

Revision ID: 971badc3fed3
Revises: None
Create Date: 2016-06-10 19:45:27.528110

"""

# revision identifiers, used by Alembic.
revision = '971badc3fed3'
down_revision = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Institution',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('address', sa.String(length=255), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('address'),
    sa.UniqueConstraint('name')
    )
    op.create_table('Role',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('role_name', sa.String(length=255), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('role_name')
    )
    op.create_table('Specialization',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('speciality', sa.String(length=255), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('speciality')
    )
    op.create_table('User',
    sa.Column('ci', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=50), nullable=True),
    sa.Column('password', sa.String(length=16), nullable=True),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('last_name', sa.String(length=255), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('role', sa.String(length=255), nullable=True),
    sa.ForeignKeyConstraint(['role'], ['Role.id'], ),
    sa.PrimaryKeyConstraint('ci'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('username')
    )
    op.create_table('Appointment',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('patient', sa.Integer(), nullable=False),
    sa.Column('doctor', sa.Integer(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('description', sa.String(length=500), nullable=False),
    sa.ForeignKeyConstraint(['doctor'], ['User.ci'], ),
    sa.ForeignKeyConstraint(['patient'], ['User.ci'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('DoctorProfile',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ci_user', sa.Integer(), nullable=False),
    sa.Column('sex', sa.String(length=10), nullable=True),
    sa.Column('date_of_birth', sa.Date(), nullable=True),
    sa.Column('marital_status', sa.String(length=15), nullable=True),
    sa.Column('telephone', sa.String(length=15), nullable=True),
    sa.Column('address', sa.String(length=100), nullable=True),
    sa.Column('habilities', sa.String(length=500), nullable=True),
    sa.Column('pregrade', sa.String(length=100), nullable=True),
    sa.Column('postgrade', sa.String(length=100), nullable=True),
    sa.Column('experience', sa.String(length=500), nullable=True),
    sa.Column('courses', sa.String(length=500), nullable=True),
    sa.Column('publications', sa.String(length=500), nullable=True),
    sa.Column('awards', sa.String(length=500), nullable=True),
    sa.ForeignKeyConstraint(['ci_user'], ['User.ci'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('Doctor_Specialization',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('doctor', sa.Integer(), nullable=False),
    sa.Column('speciality', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['doctor'], ['User.ci'], ),
    sa.ForeignKeyConstraint(['speciality'], ['Specialization.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('PatientProfile',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ci_user', sa.Integer(), nullable=False),
    sa.Column('sex', sa.String(length=10), nullable=True),
    sa.Column('date_of_birth', sa.Date(), nullable=True),
    sa.Column('marital_status', sa.String(length=15), nullable=True),
    sa.Column('telephone', sa.String(length=15), nullable=True),
    sa.Column('address', sa.String(length=100), nullable=True),
    sa.Column('heigth', sa.String(length=15), nullable=True),
    sa.Column('weigth', sa.String(length=15), nullable=True),
    sa.Column('blood_type', sa.String(length=3), nullable=True),
    sa.Column('diabetic', sa.String(length=3), nullable=True),
    sa.Column('allergies', sa.String(length=500), nullable=True),
    sa.Column('emergency_contact', sa.String(length=100), nullable=True),
    sa.Column('emergency_number', sa.String(length=15), nullable=True),
    sa.Column('comments', sa.String(length=500), nullable=True),
    sa.ForeignKeyConstraint(['ci_user'], ['User.ci'], ),
    sa.PrimaryKeyConstraint('id')
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('PatientProfile')
    op.drop_table('Doctor_Specialization')
    op.drop_table('DoctorProfile')
    op.drop_table('Appointment')
    op.drop_table('User')
    op.drop_table('Specialization')
    op.drop_table('Role')
    op.drop_table('Institution')
    ### end Alembic commands ###
